apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-demployment-replicas
  labels:
    app  : my-k8s-application
    env: prod
    owner: DmitrySmolkiy
spec:
  replicas: 3
  selector:
    matchLabels:
      project: cia
  template:
    metadata:
      labels:
        project: cia
    spec:
      containers:
        - name: cia-web
          image: tomcat
          ports:
            - containerPort: 8080
