apiVersion: v1
kind: Pod
metadata:
  name: my-app2
  labels:
    env  : prod
    app  : main
    tier : frontend
    owner: DenisAstahov
spec:
  containers: 
    - name: container-web
      image: httpd:latest
      ports: 
        - containerPort: 80

    - name: container-api
      image: nginx
      ports: 
        - containerPort: 80
